name: square_eyes
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - isort
  - jupyterlab=2
  - jupyterlab_code_formatter
  - matplotlib
  - nodejs
  - numpy
  - opencv
  - pandas
  - pip
  - python
  - scikit-learn
  - scipy
  - seaborn
  - tensorflow=2
  - swifter
  - dask
  - pip:
    - plaidml-keras
    - plaidbench