name: square_eyes
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.11
  - black
  - ffmpeg
  - ipykernel
  - ipython
  - ipywidgets
  - isort
  - jupyter>=1.0.0
  - keras=2.12.0
  - numpy=1.23.5
  - pip>=23.0.1
  - pytesseract
  - pytorch
  - pytorch-cuda=11.8
  - setuptools
  - tensorflow=2.12.0
  - torchaudio
  - torchvision
  - pip:
      - opencv-python==4.7.0.72
      - ultralytics
