name: square_eyes
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - isort
  - jupyterlab=2.1.5
  - jupyterlab_code_formatter=1.3.1
  - keras
  - matplotlib
  - nodejs
  - numpy
  - opencv
  - pandas
  - pip
  - python
  - scikit-learn
  - scipy
  - seaborn
  - tensorflow=2
  - swifter
  - dask
  - pip:
    - plaidml-keras
    - plaidbench