site_name: Square Eyes Documentation
plugins:
  - search
  - git-authors
  - git-revision-date-localized
  - mkdocstrings
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
theme:
  name: material
  features:
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    # - navigation.indexes
    - navigation.tracking
    - search.suggest
    - search.highlight
    # - toc.integrate
    - toc.follow
  palette:
    scheme: default
    primary: custom
    accent: custom
  logo: assets/SquareEyes.png
  favicon: assets/SquareEyes.png
extra_css:
  - stylesheets/acu.css
repo_url: https://github.com/Motivation-and-behaviour/squareeyes
nav:
  - Home: index.md
  - Coding Manual:
      - coding_manual/index.md
      - Coder Training: coding_manual/coder_training.md
      - Ethics:
          - coding_manual/ethics/index.md
          - coding_manual/ethics/guidelines.md
          - coding_manual/ethics/processes.md
          - coding_manual/ethics/declaration.md
      - Coding Rules:
          - coding_manual/coding_rules/index.md
      - Timelapse Software:
          - coding_manual/timelapse/index.md
      - Practice and Evaluation: coding_manual/practice_and_evaluation.md
  - Model Docs:
      - model_docs/index.md
