site_name: Square Eyes Documentation
plugins:
  - git-authors
  - git-revision-date-localized
  - glightbox:
      auto_caption: true
  - mkdocstrings
  - search
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - assets/glossary.md
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - toc:
      permalink: true
theme:
  name: material
  features:
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    # - navigation.indexes
    - navigation.tracking
    - search.suggest
    - search.highlight
    # - toc.integrate
    - toc.follow
  palette:
    scheme: default
    primary: custom
    accent: custom
  logo: imgs/SquareEyes.png
  favicon: imgs/SquareEyes.png
extra_css:
  - stylesheets/extra.css
repo_url: https://github.com/Motivation-and-behaviour/squareeyes
nav:
  - Home: index.md
  - Coding Manual:
      - coding_manual/index.md
      - Coder Training: coding_manual/coder_training.md
      - Ethics:
          - coding_manual/ethics/index.md
          - coding_manual/ethics/guidelines.md
          - coding_manual/ethics/declaration.md
      - Coding Process:
          - coding_manual/coding_rules/index.md
          - coding_manual/coding_rules/rules.md
          - coding_manual/coding_rules/procedures.md
          - coding_manual/coding_rules/codebook.md
      - Timelapse Software:
          - coding_manual/timelapse/index.md
          - coding_manual/timelapse/setup.md
          - coding_manual/timelapse/coding.md
      - Practice and Evaluation: coding_manual/practice_and_eval.md
      - Summary and Checklist: coding_manual/checklist.md
  - Model Docs:
      - model_docs/index.md
      - model_docs/install.md
