on:
  push:
    branches:
      - main
      - master

name: mkdocs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.11
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install dependencies
        run: |
          pip install \
            mkdocs-material \
            mkdocs-git-revision-date-localized-plugin \
            mkdocs-git-authors-plugin \
            mkdocstrings
      - name: Build docs
        run: mkdocs gh-deploy --force
