on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

name: mkdocs

jobs:
  check-deploy:
    runs-on: ubuntu-latest
    outputs:
      deploy-status: ${{ steps.check.outputs.triggered }} 
    steps:
      - name: Check for deploy trigger
        id: check
        uses: shanegenschaw/pull-request-comment-trigger@v2.1.0
        with:
          trigger: '/deploy'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

  deploy:
    needs: check-deploy
    if: (github.event_name == 'push') || (needs.check-deploy.outputs.deploy-status == 'true')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.11
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install dependencies
        run: |
          pip install \
            mkdocs-material \
            mkdocs-git-revision-date-localized-plugin \
            mkdocs-git-committers-plugin-2 \
            mkdocstrings \
            mkdocs-glightbox
      - name: Build docs
        run: mkdocs gh-deploy --force
